### ISSUE TITLE
Feature request: allow to visualize tensorial properties on structures

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/chemiscope#118]
The idea would be to add the ability to show vector properties as arrows, and rank-2 tensorial properties as ellipsoïds, à-la shiftml.org.

Additionally, we could represent scalar properties using colors on the structure side itself.

Like #117, most visualization engines give us primitives to build such visualizations, and most of the work is in defining the input format for vector/tensorial properties; and passing said data to the visualization engine.

**Comment by ceriottm** [comment]
took more than two years, but shapes are now fully implemented with #292. color-coding is WIP with #293, so I'll leave this open.
