### ISSUE TITLE
Scroll to zoom use different directions for map and structure

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/chemiscope#12]
Scrolling in one direction increases zoom level on the map but decreases the one for the structure. This is surprising for the users.

I don't know if plotly or jsmol can be configured to use "reverse" zoom. If not, a possibility would be to intercept the wheel event and invert the sign before allowing handling by the libraries.

**Comment by cbenmahm** [comment]
This is still present in chrome and firefox on macos.

**Comment by Luthaf** [comment]
I think this is fallout from the update to 3Dmol. I missed this behavior when updating (that's why we need tests!!!)
