### ISSUE TITLE
Display of environments for atoms at the boundary 

### ISSUE THREAD

**Issue by sandipde** [lab-cosmo/chemiscope#133]
Hello, 
Great job with the chemiscope and I am hoping to use it more and more in my work. For simple stuff it worked really great but I hit some corner cases and it would be nice to have solution at some point of time.  The most annoying one is the display of local environment for a atom that is near periodic boundary. The highlight portion does not go across the box. Also the replicated unitcell does not highlight the replica atoms which would have by passed this problem.  See the screeshot for your zeolite example. 
![image](https://user-images.githubusercontent.com/11316489/120010608-9eede300-bfdd-11eb-95e5-d8ddf914e85a.png)

**Comment by Luthaf** [comment]
> Also the replicated unitcell does not highlight the replica atoms which would have by passed this problem.

This should work if you are using a 3x3x3 supercell (to ensure there is a replicated cell on both sides of the central one). While it is not ideal, it should allow simple visualization, especially in conjunction with `style: hide` for  background atoms (in advanced environments options).

**Comment by sandipde** [comment]
@Luthaf I see ! Thanks for the tip. Will try again.

**Comment by sandipde** [comment]
Okay ..so this workaround solved the proble. If you prefer you can close this issue.

**Comment by ceriottm** [comment]
nono, this is a long-standing issue and I think we need a better solution.
there are many issues, you can click on atoms that are not environment
centers, and say you have only a few significant environments over a huge
structure, the json is huge just to hold NaNs.

**Comment by Luthaf** [comment]
Are you talking about #134 and not this issue @ceriottm? But I agree we could find a better way to display environments at the boundary of the cell.

**Comment by ceriottm** [comment]
Ah yes, I meant #134. I don't know, we could have a "border" option if it's
possible - but a 3x3x3 cell seems a good enough solution 90% of the time

**Comment by Luthaf** [comment]
Let's close this saying that a 3x3x3 cell should be enough, and if someone comes up with a use case for something else they can open a new issue!
