### ISSUE TITLE
Zeolites environments centering does not work

### ISSUE THREAD

**Issue by jakublala** [lab-cosmo/chemiscope#159]
When 'center' is on, the structure viewer centres on the centre of the molecule rather than the actual centre of the environment one considers.

**Comment by Luthaf** [comment]
That's really weird, since the CSD/chemical shielding example works fine ...

**Comment by jakublala** [comment]
> That's really weird, since the CSD/chemical shielding example works fine ...

Yes, exactly. I was surprised by that as well, but for some reason (at least on my machine) the zeolite one does not work.

**Comment by ceriottm** [comment]
I have further investigated this and found out the problem has to do with the number of replicated cells.
If it is odd, it just works, if it's even...
![image](https://user-images.githubusercontent.com/1118823/150308654-89980233-5fd2-4d3e-a178-89a8a195062b.png)
