### ISSUE TITLE
Color atoms by property

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/chemiscope#229]
Would be interesting to have the possibility of coloring atoms by an atomic property. The option could be active any time there are environment properties defined, and it could use same color schemes as for the map.

**Comment by ceriottm** [comment]
@jduerholt  Want to help?

**Comment by jduerholt** [comment]
@Luthaf knows about my very limited java script capabilities ;) Perhaps he can give a bit advise how to actually implement it and then we can see what I can actually contribute ;)

**Comment by jduerholt** [comment]
Hi Guillaume, 

sorry for my late response, I was travelling ;) This indeed sounds like not best entry point also with respect to my limited java script knowledge. Nevertheless, I am very interested in this feature as this could be really powerful in some scenarios.

Best,

Johannes

**Comment by ceriottm** [comment]
Implemented through #312  (and previous PRs)
