### ISSUE TITLE
Request for guidence

### ISSUE THREAD

**Issue by yunjian-hash** [lab-cosmo/chemiscope#235]
<img width="1084" alt="screenshot" src="https://user-images.githubusercontent.com/75162924/171549185-11bc3268-2d2f-49ae-95a6-8a0fd72a1392.png">

Dear developers,

I am so interested of your example picture showed in the main page as attached. I am wondering how to calculate and picture of it, i.e. how to calculate the electron affinity energy for every frames and input them with the trajectory and CVs. Could you please provide some guidence and the actual files for me to learn? Thanks so much

Best wishes,
Yunjian Li

**Comment by Luthaf** [comment]
Hi! 

The physical properties in this dataset (including electron affinity) come from this paper: https://iopscience.iop.org/article/10.1088/1367-2630/15/9/095003. They used DFT level calculations with FHI-AIMS and ORCA depending on the property.

The CV (collective variables) where computed using a sketch-map dimensionality reduction based on SOAP vectors, as described in https://pubs.rsc.org/en/content/articlelanding/2016/CP/C6CP00415F. 

You can find all of this information by clicking on the title of the plot (`Qm7b` here), which opens a small window with the dataset metadata.

----

For physical properties, you will have to use some simulation software (DFT or not) to compute the properties you are interested into for your data. 

For the collective variables, we have an example of how to compute a PCA of SOAP vectors here: https://github.com/lab-cosmo/chemiscope/blob/c3e0cfd4835ac0a8547d78a2aebbb1f34d5a71c0/python/examples/molecular_map.py, you should be able to modify the code to suit your needs! In particular, if you are working with full stuctures and not atomic environments, you'll want to average the SOAP vectors over all atoms in a structure before doing a PCA with them.

**Comment by yunjian-hash** [comment]
> Hi!
> 
> The physical properties in this dataset (including electron affinity) come from this paper: https://iopscience.iop.org/article/10.1088/1367-2630/15/9/095003. They used DFT level calculations with FHI-AIMS and ORCA depending on the property.
> 
> The CV (collective variables) where computed using a sketch-map dimensionality reduction based on SOAP vectors, as described in https://pubs.rsc.org/en/content/articlelanding/2016/CP/C6CP00415F.
> 
> You can find all of this information by clicking on the title of the plot (`Qm7b` here), which opens a small window with the dataset metadata.
> 
> For physical properties, you will have to use some simulation software (DFT or not) to compute the properties you are interested into for your data.
> 
> For the collective variables, we have an example of how to compute a PCA of SOAP vectors here: https://github.com/lab-cosmo/chemiscope/blob/c3e0cfd4835ac0a8547d78a2aebbb1f34d5a71c0/python/examples/molecular_map.py, you should be able to modify the code to suit your needs! In particular, if you are working with full stuctures and not atomic environments, you'll want to average the SOAP vectors over all atoms in a structure before doing a PCA with them.

Thanks very much for your kind instructions.  For physical properties, I only known that the property calculation is for the single frame, thus, how can I compute the physical properties, like electron affinity, for every frames in my trajectory and collected them as an input in chemiscope? Could you please give a more specific instructions or the actual files for me to practice? Thanks so much.

**Comment by Luthaf** [comment]
You can do the exact same thing you did in #234 when loading your `CN(Ca_Os)` and `CN(Ca_Ow)` properties. Depending on which software you are using, you'll need to write some code to load the data you want in a python list and then pass it to chemiscope.

> For physical properties, I only known that the property calculation is for the single frame,

If you know how to compute properties for a single structure, you can start calculations in a loop to compute the same thing for multiple structures. I'm afraid we can not help you much more: chemiscope job starts once you have everything computed and available as Python objects.
