### ISSUE TITLE
Save widget settings along with the widget

### ISSUE THREAD

**Issue by rosecers** [lab-cosmo/chemiscope#243]
Enable saving of widget settings, so one could call 

```
widget = chemiscope.show(..., settings=dict(...))
widget.save('chemiscope.json.gz')
```
and have the settings save with the widget.

**Comment by ceriottm** [comment]
I don't know when it was done, but this now works. you can even adjust the settings from the widget, and it will be saved. seems to have an issue saving multiple panels though
