### ISSUE TITLE
Lots of stuff out of date in the documentation

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/chemiscope#259]
Chemiscope has evolved a lot over the past year, and the documentation needs to be updated a bit. Things I noticed quickly, probably more to find:
* The about box mentions GPL license for JMol, but we don't use JMol anymore
* Many of the figures in the docs are screenshots of an old interface
* The example of usage of the web components, https://chemiscope.org/docs/embedding.html#usage-example doesn't seem to work (or at least, we should explain how that HTML can be used
* We should check that the schema at https://chemiscope.org/docs/tutorial/input-reference.html is up-do-date.

Bonus: figuring out how to make sure the documentation doesn't get out-of-date again.

**Comment by Luthaf** [comment]
> The about box mentions GPL license for JMol, but we don't use JMol anymore

Will be fixed by #256

> The example of usage of the web components, https://chemiscope.org/docs/embedding.html#usage-example doesn't seem to work (or at least, we should explain how that HTML can be used

I'll have a look, but this code is missing the dataset loading part, meaning one can not just copy/paste it around.

**Comment by jwa7** [comment]
Just to add to this - there should be a section in the README that highlights that chemiscope can be easily installed for use in jupyter notebooks simply by using `pip install chemiscope` and not going through all the npm build/install process
