### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by rosecers** [lab-cosmo/chemiscope#274]
Resources on why this is important:
https://www.git-tower.com/learn/git/faq/git-rename-master-to-main
https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

This is a fairly easy fix, but has to be done directly to the main branch, and not possible to do it via PR.

It is becoming very uncommon to have a `master` branch, and it's ruining my muscle memory typing.

**Comment by rosecers** [comment]
Resurrecting this, as `main` is becoming the predominant option for many repositories, my tab completion is being messed with. @Luthaf

**Comment by rosecers** [comment]
Would be more than happy to do it, given the access. I know you don't necessarily see it as important but others do

**Comment by Luthaf** [comment]
Done by @rosecers!
