### ISSUE TITLE
Include chemiscope in docs using sphinx

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/chemiscope#276]
It would be very nice to be able to include "passive" chemiscope viewers into autogenerated documentations, using sphinx or perhaps nbsphinxgallery.

**Comment by ceriottm** [comment]
I think that generating a static image is the best way to proceed, if it's easy to do. The level of interactivity of the embedded ipywidgets is very limited in all cases because you can't really use the evenfullness outside individual widgets.

**Comment by Luthaf** [comment]
The sphinx-gallery seems to be the easiest one to fix: we mainly need to add a `__repr_html__` function to `ChemiscopeWidget` and friends, 

https://github.com/lab-cosmo/chemiscope/blob/9b5c9b12b1b005a599488bf867a69d02f8c823e0/python/chemiscope/jupyter.py#L60

containing the same kind of HTML as the one we are using from the JS side:

https://github.com/lab-cosmo/chemiscope/blob/9b5c9b12b1b005a599488bf867a69d02f8c823e0/python/jupyter/src/widget.ts#L108-L134

The remaining question is how to insert the chemiscope javascript in there. We could load it from `https://chemiscope.org`, or one of the CDN based on top of npm?

**Comment by sandipde** [comment]
This would be very useful. Not sure if you already know this ..ngl  viewers are possible to be included in the sphinxdoc directly from.notebook render without any additional steps.

**Comment by ceriottm** [comment]
This is now fully implemented cf #340  and #341
