### ISSUE TITLE
Add arrows as predefined shape type on the JS side

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/chemiscope#291]
> Regarding arrows: should we have these as predefined shape type inside chemiscope? This will save a lot of space by not requiring to store all the vertices/simplices in the file, but instead generate them on the JS side like we do for ellispoids.

_Originally posted by @Luthaf in https://github.com/lab-cosmo/chemiscope/issues/289#issuecomment-1695523016_

**Comment by ceriottm** [comment]
Fixed in #292
