### ISSUE TITLE
Better documentation needed for write_input(settings = ...)

### ISSUE THREAD

**Issue by rosecers** [lab-cosmo/chemiscope#295]
In the [docs](https://chemiscope.org/docs/tutorial/input.html), there's minimal about how to export a map with desired settings.

**Comment by Luthaf** [comment]
> Possible entries for the settings dictionary are documented in the chemiscope input file reference.

This should be a link to https://chemiscope.org/docs/tutorial/input-reference.html. We could also split the input reference in two (separate the data from the settings) and link to the second part.
