### ISSUE TITLE
Obtaining "incorrect header check" in Sphinx

### ISSUE THREAD

**Issue by andrewtarzia** [lab-cosmo/chemiscope#359]
Dear all,

Thank you for the great project!

I am interested in embedding access to a database in a sphinx page through read the docs, and I followed the instructions in the documentation for this process.

I am testing it with the default Arginine-Dipeptide `.json`.

After building with read the docs, I get a yellow box saying `incorrect header check`, which disappears quite quickly after.

Because this file, and my other test file, both work when uploaded to chemiscope, I was hoping you could point me in the right direction to understanding this issue?

**Comment by ceriottm** [comment]
Hi, it's strage, I tried to embed Arginine-Dipeptide.json.gz using the chemiscope directive, and it displays without any warning. The error seems to come from loading one of the js dependencies, maybe from the browser js console you can get some more information of what exactly is failing. Try to run on a different system

**Comment by andrewtarzia** [comment]
My guess (from a very naive stand-point with web development) is there is an issue with how read-the-docs is building it, because it is occurring on every device/browser I have.

Here is a link to the page, by the way: https://cgmodels.readthedocs.io/en/latest/tester.html 

I am using the same docs building process I would for a Python package. But looking through your code, it seems you build the docs through a github action that uses npm rather than read-the-docs? Is that necessary for the docs, or just the app?

**Comment by ceriottm** [comment]
Hm. Interesting. I'm not sure we ever tried to include this in a readthedocs-generated documentation.  It looks like it doesn't install some of the headers it needs, the readthedocs site doesn't seem to have chemiscope-sphinx.js 
@Luthaf do you see an obvious issue?

**Comment by Luthaf** [comment]
OK, I found it. The code in chemiscope-sphinx is assuming the data is gzipped, and fails with this error if it is not. I'll try to fix this!

**Comment by andrewtarzia** [comment]
I guess that is a good assumption for saving data!

**Comment by Luthaf** [comment]
So #360 should properly detect if the data we get is gzipped or not. Until we release it, could you try using a gzipped version of the JSON file and load that?

**Comment by andrewtarzia** [comment]
Yes, for now, while I test this plan, I will use json.gz.

Thank you for your help!

**Comment by ceriottm** [comment]
Amazing how "workflow lock-in" makes it hard to detect this kind of errors. We only ever use gzipped jsons, so I would have never caught this.

**Comment by andrewtarzia** [comment]
It always helps having the "un-initiated" try to do something aha

I may have a bunch more questions as I try to get this use-case working!

**Comment by ceriottm** [comment]
released a fix, pls try again and let us know if it works for non-gzipped jsons

**Comment by andrewtarzia** [comment]
A json file works a charm now - thank you!
