### ISSUE TITLE
Web-App fails to start locally

### ISSUE THREAD

**Issue by sachingodishela** [lab-cosmo/chemiscope#364]
Tried running the webapp locally, facing this issue at `npm start`:
![image](https://github.com/user-attachments/assets/bd8daf25-1e25-479c-9410-d9396cf7ec78)

My system config:
- Distribution: Ubuntu 22
- Node Version: 20.17.0
- NPM Version: 10.8.2
- Arch: x86_64

**Comment by Luthaf** [comment]
This looks like a partial clone of the repo, and git failing to find tags. How did you get the source code? With a full `git clone` or something else? You could try running `git fetch --prune --unshallow --tags` to fetch the full history which is used by `git describe`.

**Comment by sachingodishela** [comment]
I had forked just the main branch. That was the issue, thanks.
