### ISSUE TITLE
chemiscope local web app size 0

### ISSUE THREAD

**Issue by bernstei** [lab-cosmo/chemiscope#369]
I have an input file I'm creating with `write_input`, and I want to use the species of the atoms as a property to control some aspect of visualization, probably size. I add it to the `Atoms` object with `atoms.new_array("Z", atoms.numbers)`, and then interactive set size as coming from `"Z"`.  However, for Cu Al, Zs 29 and 13, I don't get circles that are off by a factor of ~2, but rather tiny specks, and reasonable size circles.

Is setting `size` from a property reasonably tested, such that this is surprising? Or is it just something that's not well supported?  Either way I can try to do a more complete bug report.

**Comment by ceriottm** [comment]
Hello! It should work pretty well, this is something we do often. See e.g. this to give you an idea of how property value and size should compare
![Image](https://github.com/user-attachments/assets/1d4bff77-a957-420c-8b4c-815e92bf9a08)

One can never exclude a bug though. If you upload the chemiscope.json file, we can have a look.

**Comment by ceriottm** [comment]
Actually, I think I know what your problem is. The size is "rescaled" so that the smallest value is "tiny" and the largest a given "reasonable" size. There isn't really a way to set it to be actually proportional to the value in an "absolute" way. One would basically need to add "range" properties as there are for other indicators such as color and axis range. 
It's not a bad "first issue" if you feel like having some typescript fun ^^

**Comment by bernstei** [comment]
Maybe it's just that the tiny is too small in my system, perhaps because I have 2-3 widely separated clumps?

**Comment by bernstei** [comment]
Even with size fixed, something weird is going on.  I did symbol by a categorical property (config_type), and the squares (circled in red pen) are much smaller than the circles.  Is this also normal?

![Image](https://github.com/user-attachments/assets/f413819b-c460-482e-bc87-cf68a21b1094)

**Comment by ceriottm** [comment]
So, I tweaked a few things that should now work better, pls have a look. Your second issue looks strange. Here point size, color and z coordinates are all expressions of the same quantity, and all sizes look proportionate independent of the symbol
![Image](https://github.com/user-attachments/assets/8dda3935-45a2-403e-9eaf-0c977190adb9)
See if it also breaks with the branch (if you want to run locally you need the whole node.js stack, and launch `npm install; npm start` from the repo root, then you should be able to open localhost:8080 and see the web interface.

**Comment by bernstei** [comment]
That's more like what I expected.  Let me check the `size-cleanup` branch and see how it behaves.

**Comment by bernstei** [comment]
`size-cleanup` definitely looks better with fixed size now - the squares are comparable to the circles, which I like. It also works sensibly with Z for size, as long as Z is a number.  I had a string Z, so I could use it for symbol type, and then it behaved weirdly.  Not sure if it's worth checking for that situation.

Also, the default colormap has an issue - it goes black to yellow, and if I have many spots at the bottom of the range (which is the case if it's a categorical property, like config_type) the black spots merge into a uniform blob, because the outlines are _also_ black.

**Comment by ceriottm** [comment]
Excellent, we'll go ahead and merge the PR so you have something that works. I also added a `proportional` mode which doesn't stretch the range, but is proportional to the actual magnitude.
I'd be tempted to say that the default colormap is a wontfix issue, as you can always pick a different colormap. we could always switch to viridis but it's a bit boring :-)

**Comment by bernstei** [comment]
Thanks.  What about making the marker *outlines* always be contrasty with the actual color as selected by the colormap for each marker?  This only happens because the marker and the outline are both black.

**Comment by ceriottm** [comment]
That requires substantial additional complication and it looks like a sufficiently narrow corner case to warrant that. Maybe one thing that you didn't know: you can select the color palette when you call `write_input` (the `settings` option accepts a dictionary with the entire option set), so you can make sure that your .json file will load already with a palette that does not have this problem.  
You can experiment in a notebook using `chemiscope.show` and then only write when you're happy with the visualization. You can also edit the visualization options in the online viewer and then save the .json again, and it'll incorporate the settings.

**Comment by ceriottm** [comment]
@bernstei  just to add that if you feel this "contrasty outline" is important for your workflow and you can't fix it with the workarounds we discussed you should open another issue, but it'll be low priority on our side so code contributions will also be much welcome ^_^.

**Comment by bernstei** [comment]
I can definitely live with using a different palette.  If I do feel that it's worth a proper fix, I'll try to see if I can understand the code structure enough to make a PR.
