### ISSUE TITLE
Chemiscope not loading

### ISSUE THREAD

**Issue by andrewtarzia** [lab-cosmo/chemiscope#375]
I am seeing this error upon accessing chemiscope visualiser (https://chemiscope.org/) now on Chrome and Firefox:
![Image](https://github.com/user-attachments/assets/1d3e5e4e-835d-4ff7-9a31-ceb6fc39f901)

**Comment by andrewtarzia** [comment]
It seems back!

**Comment by ceriottm** [comment]
Yes, was a side-effect of updating the node.js dependencies. Almost all fixed it seems

**Comment by andrewtarzia** [comment]
I am still seeing some issues when building from the pip version, I guess that will be updated too?

**Comment by ceriottm** [comment]
#376

**Comment by Luthaf** [comment]
> I am still seeing some issues when building from the pip version, I guess that will be updated too?

You mean the version you get with `pip install chemiscope`? Or building a local version from a git checkout?

**Comment by andrewtarzia** [comment]
> > I am still seeing some issues when building from the pip version, I guess that will be updated too?
> 
> You mean the version you get with `pip install chemiscope`? Or building a local version from a git checkout?

The pip installable version - built through read-the-docs

**Comment by andrewtarzia** [comment]
My chrome console output, if this helps:
![Image](https://github.com/user-attachments/assets/f19c112e-52e3-4430-801e-6e267aaf9e2d)

**Comment by Luthaf** [comment]
Ok, We might need to do a patch release with the same fix that we had to use for the chemiscope website.

**Comment by Luthaf** [comment]
Ok, the new release (0.8.1) is on PyPI. Could you check and let me know if it works for you?

**Comment by andrewtarzia** [comment]
Worked a charm. Thank you both for your help!
