### ISSUE TITLE
show all atoms in a geometry configuration even if only a subset have points in the map

### ISSUE THREAD

**Issue by bernstei** [lab-cosmo/chemiscope#382]
It would be very helpful to be able to show an entire geometry including all atoms but only include a subset of the atoms in the map (of PCA coordinates, in my case). Is that possible to do right now?  For the geometries I'm using `all_atomic_environments` to pass into `write_input`, which then requires that there be a map coordinate _for every atom_ from what I can tell.  Is it possible to set (or is it already possible and I just missed it) the map coordinates for some atoms to `NaN` or `None`, so the points don't show up on the map, but are still shown in the geometry viewer?

**Comment by ceriottm** [comment]
You mean a sparse selection of environments? This is possible already, you just have a list of enviornments in the form `[i_structure, j_atom, cutoff]` and have properties defined only for those. cutoff is only used in the visualization at the moment.

**Comment by bernstei** [comment]
I think that's sufficient. So I should be able take the output of `all_atomic_environments` and select just the subset that corresponds to atoms that I want to have visualized in the map?  Let me try that, and if it works, I'll close this issue.  If not, I'll explain what I need (which may be just a note in the documentation)

**Comment by bernstei** [comment]
Yes, that seems to work. My current code is bit cumbersome in constructing the relevant arrays (properties) and lists (envs), but it works. I'll have to think about whether I can do that more cleanly.  It might be kind of nice to be able to entirely include/exclude points from the map interactively, by a categorical property (or range of a numerical one).
