### ISSUE TITLE
map png save uses wrong height

### ISSUE THREAD

**Issue by bernstei** [lab-cosmo/chemiscope#392]
The map png save button uses the width for both the width and the height of the saved bitmap. svg seems to use width for width and height for height, as I'd have expected.

https://github.com/lab-cosmo/chemiscope/blob/0bb0f8d93140048883938fcded2489b9a89b8fdf/src/map/map.ts#L138

**Comment by Luthaf** [comment]
This looks like a typo. As a simple fix for the resolution, we could try to use the double of the current size. I'll need to check if plotly will actually render a higher resolution image though.

**Comment by bernstei** [comment]
I've definitely changed the 600 -> 1200. or 2400 in the web version, by editing `map.ts`, and the output is higher resolution.  The problem is that the glyph sizes (and font sizes, I think) are apparently fixed in pixels, so they look smaller in the output.  There's a scale parameter that I think would address this, but it's only in the python plotly output function, not in the TS interface that's used by chemiscope.

**Comment by Luthaf** [comment]
Actually, the JS function accepts a `scale` parameter, but it is not documented. This should be fixed in #393
